// demo-project/02-vue3-ssr/src/views/Home.vue
<script setup>
import { ref } from 'vue'

const counter = ref(100)
function onAddButtonClick() {
  counter.value++
}
</script>

<template>
  <div class="home" style="border: 1px solid green; margin: 10px">
    <h1>Home</h1>
    <div>{{ counter }}</div>
    <button @click="onAddButtonClick">加1</button>
  </div>
</template>

<style scoped></style>

// demo-project/04-react-ssr/src/pages/Home.jsx
import React, { memo, useState } from 'react'

const Home = memo(() => {
  const [counter, setCounter] = useState(100);

  return (
    <div style={{border: '1px solid blue'}}>
      <h1>Home</h1>
      <div>counter: {counter}</div>
      <button onClick={() => setCounter(counter + 1)}>+1</button>
    </div>
  )
})

export default Home
