// demo-project/oppo-nuxt/components/grid-view/index.vue
<script setup lang="ts">
import { IProductDetailss } from '~/types/home';

interface IProps {
  productsDetal: IProductDetailss[]
}

withDefaults(defineProps<IProps>(), {
  productsDetal: () => []
})
</script>

<template>
  <div class="grid-view">
    <template v-for="item, index of productsDetal" :key="itme.id">
      <div class="grid-view">{{ item.title }}</div>
    </template>
  </div>
</template>

<style scoped lang="scss">

</style>

// demo-project/music-next/src/components/grid-view/index.tsx
import type { AllProduct, HotProduct } from '@/types/product'
import React, { memo } from 'react'
import type { FC, ReactNode } from 'react'
import { Col, Row } from 'antd'
import GridViewItem from '../grid-view-item'
import styles from './index.module.scss'

interface IProps {
  children?: ReactNode
  products: HotProduct[] | AllProduct[]
}
const GridView: FC<IProps> = memo(props => {
  const { products } = props

  return (
    <div className={'grid-view'}>
      <Row>
        {products.map((product, index) => {
          return (
            <Col key={product.id} span={6}>
              <div className={styles['view-item']}>
                <GridViewItem product={product} showTip ={index === 0}></GridViewItem>
              </div>
            </Col>
          )
        })}
      </Row>
    </div>
  )
})

GridView.displayName = 'GridView'

export default GridView
