// demo-project/04-react-ssr/src/app.jsx
import React, { memo, useState } from 'react'
import { Link, useRoutes } from 'react-router-dom';
import routes from './router';

const app = memo(() => {
  const [counter, setCounter] = useState(0);

  return (
    <div style={{border: '1px solid red'}}>
      <h1>App</h1>
      <div>counter: {counter}</div>
      <button onClick={() => setCounter(counter + 1)}>+1</button>

      <div>
        <Link to="/">
          <button>Home</button>
        </Link>
        <Link to="/about">
          <button>About</button>
        </Link>
      </div>

      {/* 路由占位 */}
      {useRoutes(routes)}
    </div>
  )
})

export default app

// demo-project/02-vue3-ssr/src/App.vue
<script setup>

import { storeToRefs } from 'pinia';
import { useHomeStore  } from './store/home';

const homeStore = useHomeStore()
const { count } = storeToRefs(homeStore)

function onAddButtonClick() {
  count.value++
}
</script>

<template>
  <div class="app" style="border: 1px solid red">
    <h1>Vue3 app</h1>
    <div>{{ count }}</div>
    <button @click="onAddButtonClick">加1</button>

    <div>
      <router-link to="/">
        <button>home</button>
      </router-link>
      <router-link to="/about">
        <button>about</button>
      </router-link>
    </div>

    <router-view></router-view>
  </div>

</template>

<style scoped></style>
