// 02-vue3-ssr/src/App.vue
<script setup>
import { ref } from 'vue';

const counter = ref(100)
const onAddButtonClick = () => {
  console.log('haha')
  counter.value++
}

</script>

<template>
  <div class="app" style="border: 1px solid red;">
    <h1>Vue3 app</h1>
    <div>{{ counter }}</div>
    <button @click="onAddButtonClick">+1</button>
  </div>
</template>

<style scoped>

</style>

// demo-project/04-react-ssr/src/app.jsx
import React, { memo, useState } from 'react'
import { Link, useRoutes } from 'react-router-dom';
import routes from './router';

const app = memo(() => {
  const [counter, setCounter] = useState(0);

  return (
    <div style={{border: '1px solid red'}}>
      <h1>App</h1>
      <div>counter: {counter}</div>
      <button onClick={() => setCounter(counter + 1)}>+1</button>

      <div>
        <Link to="/">
          <button>Home</button>
        </Link>
        <Link to="/about">
          <button>About</button>
        </Link>
      </div>

      {/* 路由占位 */}
      {useRoutes(routes)}
    </div>
  )
})

export default app
